# Generated by Django 5.0.3 on 2024-04-15 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doc', '0002_demanddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_audit', models.CharField(max_length=100)),
                ('designation', models.TextField()),
                ('type_audit', models.CharField(max_length=100)),
                ('date_debut_audit', models.DateField()),
                ('date_fin_audit', models.DateField()),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('auditeurs', models.ManyToManyField(limit_choices_to={'groups__name': 'Employe'}, related_name='audits_auditors', to=settings.AUTH_USER_MODEL)),
                ('audités', models.ManyToManyField(related_name='audits_audited', to=settings.AUTH_USER_MODEL)),
                ('champ_audit', models.ManyToManyField(limit_choices_to={'groups__name': 'audit'}, related_name='audits_access', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits_auditors', to='doc.docext')),
                ('responsable_validation', models.ForeignKey(limit_choices_to={'groups__name': 'Employe'}, on_delete=django.db.models.deletion.CASCADE, related_name='audits_validator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
                ('date', models.DateField()),
                ('heure_debut', models.IntegerField()),
                ('heure_fin', models.IntegerField()),
                ('lieu', models.CharField(max_length=100)),
                ('commentaires', models.TextField()),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.audit')),
                ('created_by', models.ForeignKey(limit_choices_to={'groups__name': 'redacteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='plan_audit_created', to=settings.AUTH_USER_MODEL)),
                ('personnes_concernees', models.ManyToManyField(limit_choices_to={'groups__name': 'Employe'}, related_name='personnes_concernees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_audit_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
