# Generated by Django 5.0.3 on 2024-06-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_audit_auditeurs_alter_audit_champ_audit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='auditeurs',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='audités',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='champ_audit',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='responsable_validation',
        ),
        migrations.AddField(
            model_name='audit',
            name='statut',
            field=models.CharField(choices=[('Réalisé', 'Réalisé'), ('Non Réalisé', 'Non Réalisé')], default='Non Réalisé', max_length=20, null=True),
        ),
    ]
