# Generated by Django 5.0.3 on 2024-06-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_audit_auditeurs_remove_audit_audités_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='statut',
            field=models.CharField(choices=[('Réalisé', 'Réalisé'), ('Non Réalisé', 'Non Réalisé'), ('En attente', 'En attente')], default='En attente', max_length=20, null=True),
        ),
    ]
