# Generated by Django 5.0.3 on 2024-04-22 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauNonConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitNonConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SourceNonConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeNonConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_detection', models.DateField()),
                ('designation_produit_non_conforme', models.CharField(max_length=100)),
                ('description_non_conformite', models.TextField()),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'groups__name': 'redacteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='creer_nonConformite', to=settings.AUTH_USER_MODEL)),
                ('niveau_gravite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.niveaunonconforme')),
                ('personnes_a_notifier', models.ManyToManyField(related_name='non_conformites_a_notifier', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_nonConformite', to=settings.AUTH_USER_MODEL)),
                ('produits_non_conformes', models.ManyToManyField(related_name='non_conformites', to='produit.produitnonconforme')),
                ('source_non_conformite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.sourcenonconforme')),
                ('type_non_conformite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.typenonconforme')),
            ],
        ),
        migrations.CreateModel(
            name='FicheTraitementNonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_traitement', models.DateField()),
                ('cout_non_conformite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_rejetee', models.IntegerField()),
                ('valeur_quantite_rejetee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_declassee', models.IntegerField()),
                ('valeur_quantite_declassee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_acceptee', models.IntegerField()),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creer_ficheT_nonConformite', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_ficheT_nonConformite', to=settings.AUTH_USER_MODEL)),
                ('non_conformite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produit.nonconformite')),
            ],
        ),
        migrations.CreateModel(
            name='FicheNonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_non_conformite', models.CharField(max_length=100)),
                ('numero_OF', models.CharField(max_length=100)),
                ('numero_O', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'groups__name': 'redacteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='creer_fiche_nonConformite', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_fiche_nonConformite', to=settings.AUTH_USER_MODEL)),
                ('non_conformite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produit.nonconformite')),
            ],
        ),
        migrations.CreateModel(
            name='FicheClotureNonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitement_produit_non_conforme', models.CharField(choices=[('Cloturer', 'Clôturer'), ('NonCloturer', 'Non clôturer')], max_length=20)),
                ('date_cloture', models.DateField(default=django.utils.timezone.now)),
                ('rapport_cloture', models.TextField()),
                ('non_conformite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produit.nonconformite')),
            ],
        ),
    ]
