# Generated by Django 5.0.3 on 2024-04-22 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_fichecloturenonconformite_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.AlterField(
            model_name='fichenonconformite',
            name='non_conformite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.nonconformite'),
        ),
    ]
