# Generated by Django 5.0.3 on 2024-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_alter_fichetraitementnonconformite_non_conformite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformite',
            name='niveau_gravite',
            field=models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Élevée', 'Élevée')], default=None, max_length=50),
        ),
        migrations.RemoveField(
            model_name='nonconformite',
            name='produits_non_conformes',
        ),
        migrations.AlterField(
            model_name='nonconformite',
            name='source_non_conformite',
            field=models.CharField(choices=[('Usine', 'Usine'), ('Fournisseur', 'Fournisseur'), ('Processus de production', 'Processus de production'), ('Transport', 'Transport'), ('Stockage', 'Stockage')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='nonconformite',
            name='type_non_conformite',
            field=models.CharField(choices=[('Matière première défectueuse', 'Matière première défectueuse'), ('Erreur de production', 'Erreur de production'), ("Défaut d'emballage", "Défaut d'emballage"), ('Problème de livraison', 'Problème de livraison'), ('Mauvaise manipulation', 'Mauvaise manipulation')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='nonconformite',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_produit/'),
        ),
        migrations.DeleteModel(
            name='NiveauNonConforme',
        ),
        migrations.DeleteModel(
            name='ProduitNonConforme',
        ),
        migrations.AddField(
            model_name='nonconformite',
            name='produits_non_conformes',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='SourceNonConforme',
        ),
        migrations.DeleteModel(
            name='TypeNonConforme',
        ),
    ]
