# Generated by Django 5.0.3 on 2024-06-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_clientenquete_name_enquete'),
        ('produit', '0006_alter_fichenonconformite_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformite',
            name='reclamation_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_client_non_conforme', to='CRM.reclamationclient'),
        ),
    ]
