# Generated by Django 5.0.3 on 2024-06-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0001_initial'),
        ('produit', '0007_nonconformite_reclamation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformite',
            name='produits_non_conformes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TypeProduit_non_conforme', to='fournisseur.typeproduit'),
        ),
    ]
