# Generated by Django 5.0.3 on 2024-06-02 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RH', '0030_responsableformation_formations_concernees_and_more'),
        ('doc', '0014_alter_docext_fichier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExigenceReglementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_fiche', models.CharField(choices=[('Sécurité', 'Sécurité'), ('Environnement', 'Environnement'), ('Qualité', 'Qualité'), ('Autre', 'Autre')], max_length=50)),
                ('type_decideur', models.CharField(max_length=100)),
                ('exigence_dec', models.BooleanField(default=False)),
                ('nom_reglementation', models.CharField(blank=True, max_length=100, null=True)),
                ('applicable', models.BooleanField(default=False)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes_conformité/')),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creer_com', to=settings.AUTH_USER_MODEL)),
                ('plan_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.planaction')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.docext')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_com', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
