# Generated by Django 5.0.3 on 2024-04-05 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_fournisseur', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('raison_sociale', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('categorie', models.CharField(choices=[('cat1', 'Catégorie 1'), ('cat2', 'Catégorie 2'), ('cat3', 'Catégorie 3')], max_length=10)),
                ('type_fournisseur', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], max_length=10)),
                ('fournisseur_agree', models.BooleanField(default=False)),
                ('piece_jointe', models.FileField(upload_to='pieces_jointes/')),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('periodicite_evaluation', models.CharField(choices=[('annuelle', 'Annuelle'), ('semestrielle', 'Semestrielle'), ('trimestrielle', 'Trimestrielle')], max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseur_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('type_produit', models.CharField(max_length=100)),
                ('critere_evaluation', models.TextField()),
                ('notes', models.DecimalField(decimal_places=1, max_digits=3)),
                ('commentaires', models.TextField()),
                ('periodicite_evaluation', models.CharField(choices=[('annuelle', 'Annuelle'), ('semestrielle', 'Semestrielle'), ('trimestrielle', 'Trimestrielle'), ('mensuelle', 'Mensuelle'), ('ponctuelle', 'Ponctuelle')], max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_fournisseur_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_fournisseur_updated', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseur.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('numero_sequentiel', models.CharField(max_length=50, unique=True)),
                ('date_reclamation', models.DateField()),
                ('nom_fournisseur', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('élevée', 'Élevée')], max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('piece_jointe', models.FileField(upload_to='pieces_jointes/')),
                ('actions', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_fournisseur_created', to=settings.AUTH_USER_MODEL)),
                ('reclamation_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.reclamationclient')),
                ('type_reclamation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.typereclamation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamation_fournisseur_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
