# Generated by Django 5.0.3 on 2024-05-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamationfournisseur',
            name='type_reclamation',
            field=models.CharField(choices=[('Service', 'Service'), ('Produit', 'Produit'), ('Facturation', 'Facturation'), ('Livraison', 'Livraison'), ('Support', 'Support')], default=None, max_length=50),
        ),
    ]
