# Generated by Django 5.0.3 on 2024-05-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0002_alter_reclamationfournisseur_type_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='categorie',
            field=models.CharField(choices=[('electronique', 'electronique'), ('textile', 'textile'), ('alimentation', 'alimentation')]),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='type_fournisseur',
            field=models.CharField(choices=[('Fournisseur de matière première', 'Fournisseur de matière première'), ('Fournisseur de composants', 'Fournisseur de composants'), ('Fournisseur de produits finis', 'Fournisseur de produits finis')]),
        ),
    ]
