# Generated by Django 5.0.3 on 2024-05-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0003_alter_fournisseur_categorie_alter_fournisseur_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_fournisseur/'),
        ),
    ]
