# Generated by Django 5.0.3 on 2024-05-30 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0004_alter_fournisseur_pieces_jointes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluationfournisseur',
            name='fournisseur',
        ),
        migrations.AlterField(
            model_name='evaluationfournisseur',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_evaluation_fournisseur/'),
        ),
        migrations.AlterField(
            model_name='reclamationfournisseur',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_reclamation_fournisseur/'),
        ),
        migrations.AlterField(
            model_name='evaluationfournisseur',
            name='type_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseur.typeproduit'),
        ),
    ]
