# Generated by Django 5.0.3 on 2024-05-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0005_typeproduit_remove_evaluationfournisseur_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationfournisseur',
            name='fournisseur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fournisseur.fournisseur'),
        ),
    ]
