# Generated by Django 5.0.3 on 2024-04-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('type_indicateur', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], max_length=10)),
                ('processus_lie', models.CharField(max_length=100)),
                ('axe_politique_qualite', models.CharField(choices=[('axe1', 'Axe 1'), ('axe2', 'Axe 2'), ('axe3', 'Axe 3')], max_length=10)),
                ('type_resultat_attendu', models.CharField(choices=[('resultat1', 'Résultat 1'), ('resultat2', 'Résultat 2'), ('resultat3', 'Résultat 3')], max_length=20)),
                ('date_debut', models.DateField()),
                ('periodicite_indicateur', models.CharField(choices=[('annuelle', 'Annuelle'), ('semestrielle', 'Semestrielle'), ('trimestrielle', 'Trimestrielle'), ('mensuelle', 'Mensuelle'), ('hebdomadaire', 'Hebdomadaire'), ('quotidienne', 'Quotidienne')], max_length=20)),
                ('type_suivi', models.CharField(choices=[('manuel', 'Manuel'), ('formule', 'Formule de calcul')], max_length=10)),
                ('valeur_cible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_critique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsable_indicateur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.CharField(max_length=100)),
                ('objectif', models.TextField()),
                ('limite_critique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resultat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commentaire', models.TextField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicateur.indicateur')),
            ],
        ),
    ]
