# Generated by Django 5.0.3 on 2024-04-05 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicateur_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicateur_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suiviindicateur',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='suiviindicateur',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_indicateur_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suiviindicateur',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='suiviindicateur',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi_indicateur_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
