# Generated by Django 5.0.3 on 2024-04-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0003_axepolitiquequalite_typeindicateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicateur',
            name='pieces_jointes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsuiviindicateur',
            name='pieces_jointes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes/'),
        ),
        migrations.AddField(
            model_name='suiviindicateur',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes/'),
        ),
    ]
