# Generated by Django 5.0.3 on 2024-05-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0005_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalindicateur',
            name='pieces_jointes',
        ),
        migrations.RemoveField(
            model_name='historicalsuiviindicateur',
            name='pieces_jointes',
        ),
        migrations.RemoveField(
            model_name='indicateur',
            name='pieces_jointes',
        ),
        migrations.RemoveField(
            model_name='suiviindicateur',
            name='pieces_jointes',
        ),
        migrations.AddField(
            model_name='suiviindicateur',
            name='liste',
            field=models.ManyToManyField(to='indicateur.indicateur'),
        ),
        migrations.AlterField(
            model_name='historicalindicateur',
            name='type_suivi',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('formule', 'Formule de calcul')]),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_indicateur/'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='type_suivi',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('formule', 'Formule de calcul')]),
        ),
        migrations.AlterField(
            model_name='suiviindicateur',
            name='indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateur_reference', to='indicateur.indicateur'),
        ),
        migrations.AlterField(
            model_name='suiviindicateur',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_suivi/'),
        ),
        migrations.AlterField(
            model_name='historicalindicateur',
            name='processus_lie',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicateur.processus'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='processus_lie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicateur.processus'),
        ),
    ]
