# Generated by Django 5.0.3 on 2024-06-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0006_processus_remove_historicalindicateur_pieces_jointes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicateur',
            name='axe_politique_qualite',
            field=models.CharField(choices=[('satisfaction_client', 'Satisfaction Client'), ('amélioration_continue', 'Amélioration Continue'), ('conformité', 'Conformité')], default='satisfaction_client', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalindicateur',
            name='processus_lie',
            field=models.CharField(choices=[('production', 'Production'), ('logistique', 'Logistique'), ('achat', 'Achat'), ('vente', 'Vente')], default='production', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalindicateur',
            name='type_indicateur',
            field=models.CharField(choices=[('qualité', 'Qualité'), ('performance', 'Performance'), ('sécurité', 'Sécurité')], default='qualité', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalindicateur',
            name='type_resultat_attendu',
            field=models.CharField(choices=[('quantitatif', 'Quantitatif'), ('qualitatif', 'Qualitatif'), ('financier', 'Financier')], default='quantitatif', max_length=20),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='axe_politique_qualite',
            field=models.CharField(choices=[('satisfaction_client', 'Satisfaction Client'), ('amélioration_continue', 'Amélioration Continue'), ('conformité', 'Conformité')], default='satisfaction_client', max_length=30),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='processus_lie',
            field=models.CharField(choices=[('production', 'Production'), ('logistique', 'Logistique'), ('achat', 'Achat'), ('vente', 'Vente')], default='production', max_length=20),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='type_indicateur',
            field=models.CharField(choices=[('qualité', 'Qualité'), ('performance', 'Performance'), ('sécurité', 'Sécurité')], default='qualité', max_length=20),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='type_resultat_attendu',
            field=models.CharField(choices=[('quantitatif', 'Quantitatif'), ('qualitatif', 'Qualitatif'), ('financier', 'Financier')], default='quantitatif', max_length=20),
        ),
    ]
