# Generated by Django 5.0.3 on 2024-05-21 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RH', '0030_responsableformation_formations_concernees_and_more'),
        ('action', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('date_previsionnelle', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('ordre_du_jour', models.TextField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='meeting_attachments/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(limit_choices_to={'groups__name': 'Employe'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandeur_reunion', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='meetings_attended', to='RH.participant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion_updated', to=settings.AUTH_USER_MODEL)),
                ('type_reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_reunion', to='reunion.type')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_text', models.TextField()),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('action_prise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.actionprincipale')),
                ('created_by', models.ForeignKey(limit_choices_to={'groups__name': 'Employe'}, on_delete=django.db.models.deletion.CASCADE, related_name='decision_reunion', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_updated', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reunion.meeting')),
            ],
        ),
    ]
