# Generated by Django 5.0.3 on 2024-04-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0020_clotureformation'),
        ('reunion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings_attended', to='RH.participant'),
        ),
    ]
