# Generated by Django 5.0.3 on 2024-06-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0002_alter_meeting_type_reunion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='meeting',
        ),
    ]
