# Generated by Django 5.0.3 on 2024-06-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0004_remove_decision_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reunion.meeting'),
        ),
    ]
