# Generated by Django 5.0.3 on 2024-03-27 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('Zip_code', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau_requis', models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3'), (4, 'Niveau 4')])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_acquis', models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3'), (4, 'Niveau 4')])),
                ('commentaires', models.TextField(blank=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.competence')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EC', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FicheEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_mobile', models.CharField(max_length=15)),
                ('work_phone', models.CharField(max_length=15)),
                ('work_email', models.EmailField(max_length=254)),
                ('work_location', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('bank_account_number', models.PositiveIntegerField()),
                ('home_work_distance', models.FloatField()),
                ('martial_status', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(max_length=255)),
                ('emergency_phone', models.CharField(max_length=255)),
                ('certificate_level', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('cnss', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_address', to='RH.address')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_employees', to='RH.employe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiche_employe', to=settings.AUTH_USER_MODEL)),
                ('department', models.ManyToManyField(to='RH.department')),
                ('employe_concerné', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_employee', to='RH.employe')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RH.jobpost')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to='RH.employe')),
                ('work_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_work_address', to='RH.address')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_formation', models.CharField(max_length=255)),
                ('type_formation', models.CharField(choices=[('interne', 'Formation en interne'), ('intra', 'Formation en intra')], max_length=10)),
                ('organisme_formation', models.CharField(max_length=255)),
                ('theme_formation', models.TextField()),
                ('date_debut_formation', models.DateField()),
                ('date_fin_formation', models.DateField()),
                ('parametre_validation', models.CharField(choices=[('chaud', 'Évaluation à chaud'), ('froid', 'Évaluation à froid')], max_length=10)),
                ('date_cloture_formation', models.DateField()),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='formations_participants', to='RH.employe')),
                ('responsable_validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_responsable_validation', to='RH.employe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Formation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_participants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationChaud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('formation1', 'Formation 1'), ('formation2', 'Formation 2')], max_length=50)),
                ('date_realisation', models.DateField()),
                ('criteres', models.CharField(max_length=50)),
                ('coefficients', models.CharField(choices=[('1', 'évaluation insatisfaisante'), ('2', 'évaluation faible'), ('3', 'évaluation moyenne'), ('4', 'évaluation bonne'), ('5', 'évaluation satisfaisante')], max_length=50)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evalu_chaud', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.participant')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.participant'),
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RH.evaluationcompetence')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PA', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosteFonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_fonction', models.CharField(max_length=255)),
                ('positionnement', models.CharField(max_length=255)),
                ('mission_principale', models.TextField()),
                ('competences_requises', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite_principale', models.TextField()),
                ('relation_fonctionnelle', models.ManyToManyField(to='RH.employe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostFonction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_formation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationFroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('formation1', 'Formation 1'), ('formation2', 'Formation 2')], max_length=50)),
                ('date_realisation', models.DateField()),
                ('criteres', models.CharField(max_length=50)),
                ('coefficients', models.CharField(choices=[('1', 'évaluation insatisfaisante'), ('2', 'évaluation faible'), ('3', 'évaluation moyenne'), ('4', 'évaluation bonne'), ('5', 'évaluation satisfaisante')], max_length=50)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ManyToManyField(to='RH.employe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evalu_froid', to=settings.AUTH_USER_MODEL)),
                ('responsable_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.responsableformation')),
            ],
        ),
    ]
