# Generated by Django 5.0.3 on 2024-03-27 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0002_jobpost_updated_at_address_competence_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JobPost_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
