# Generated by Django 5.0.3 on 2024-03-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0004_rename_timezone_ficheemployee_timezone_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='prénom',
            new_name='prenom',
        ),
    ]
