# Generated by Django 5.0.3 on 2024-03-28 20:59

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0005_rename_prénom_employe_prenom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficheemployee',
            old_name='employe_concerné',
            new_name='employe_concerne',
        ),
        migrations.RemoveField(
            model_name='evaluationfroid',
            name='responsable',
        ),
        migrations.AlterField(
            model_name='ficheemployee',
            name='home_work_distance',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ficheemployee',
            name='martial_status',
            field=models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié'), ('D', 'Divorcé'), ('V', 'Veuf')], max_length=1, verbose_name='État civil'),
        ),
        migrations.AlterField(
            model_name='ficheemployee',
            name='timezone_field',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
        migrations.AlterField(
            model_name='ficheemployee',
            name='working_hours',
            field=models.FloatField(),
        ),
    ]
