# Generated by Django 5.0.3 on 2024-03-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0006_rename_employe_concerné_ficheemployee_employe_concerne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='participant',
        ),
        migrations.AddField(
            model_name='participant',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.employe'),
        ),
    ]
