# Generated by Django 5.0.3 on 2024-03-29 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0007_remove_employe_participant_participant_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='responsableformation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
