# Generated by Django 5.0.3 on 2024-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0008_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
