# Generated by Django 5.0.3 on 2024-04-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0012_competence_evaluationcompetence_ficheemployee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ficheemployee',
            name='work_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='responsableformation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
