# Generated by Django 5.0.3 on 2024-04-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0017_participant_is_user_participant_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='participants',
            field=models.ManyToManyField(related_name='formations_participants', to='RH.participant'),
        ),
    ]
