# Generated by Django 5.0.3 on 2024-04-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0018_alter_formation_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='date_cloture_formation',
        ),
        migrations.AddField(
            model_name='formation',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
    ]
