# Generated by Django 5.0.3 on 2024-04-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0019_remove_formation_date_cloture_formation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_presence', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('support_formation', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('certifications', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
            ],
        ),
    ]
