# Generated by Django 5.0.3 on 2024-05-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0020_clotureformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='date_debut_formation',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_fin_formation',
            field=models.DateField(default=None, null=True),
        ),
    ]
