# Generated by Django 5.0.3 on 2024-05-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0021_alter_formation_date_debut_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('terminé', 'terminé')], default='En attente', max_length=20),
        ),
    ]
