# Generated by Django 5.0.3 on 2024-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0022_formation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='participants',
            field=models.ManyToManyField(to='RH.participant'),
        ),
    ]
