# Generated by Django 5.0.3 on 2024-05-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0024_rename_address_name_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='formation_concerne',
        ),
    ]
