# Generated by Django 5.0.3 on 2024-05-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0026_participant_formations_concernees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationchaud',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='evaluationfroid',
            name='responsable_formation',
        ),
    ]
