# Generated by Django 5.0.3 on 2024-05-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0027_remove_evaluationchaud_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_participant/'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='responsableformation',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_responsable/'),
        ),
        migrations.AlterField(
            model_name='responsableformation',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
