# Generated by Django 5.0.3 on 2024-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0028_alter_employe_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_employe/'),
        ),
        migrations.AlterField(
            model_name='evaluationchaud',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_chaud/'),
        ),
        migrations.AlterField(
            model_name='evaluationcompetence',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_competence/'),
        ),
        migrations.AlterField(
            model_name='evaluationfroid',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_froid/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_formation/'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_job/'),
        ),
        migrations.DeleteModel(
            name='PosteFonction',
        ),
    ]
