# Generated by Django 5.0.3 on 2024-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0029_alter_employe_pieces_jointes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsableformation',
            name='formations_concernees',
            field=models.ManyToManyField(blank=True, related_name='responsables_concernes', to='RH.formation'),
        ),
        migrations.RemoveField(
            model_name='formation',
            name='responsable_formation',
        ),
        migrations.AddField(
            model_name='formation',
            name='responsable_formation',
            field=models.ManyToManyField(to='RH.responsableformation'),
        ),
    ]
