# Generated by Django 5.0.3 on 2024-06-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0030_responsableformation_formations_concernees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcompetence',
            name='skills_acquis',
        ),
        migrations.RemoveField(
            model_name='evaluationcompetence',
            name='skills_requis',
        ),
        migrations.AddField(
            model_name='evaluationcompetence',
            name='total_acquis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationcompetence',
            name='total_requis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CritereEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_acquis', models.CharField(max_length=100)),
                ('skills_requis', models.CharField(max_length=100)),
                ('note_acquis', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('note_requis', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='RH.evaluationcompetence')),
            ],
        ),
    ]
