# Generated by Django 5.0.3 on 2024-06-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0031_remove_evaluationcompetence_skills_acquis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcompetence',
            name='total_acquis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationcompetence',
            name='total_requis',
            field=models.FloatField(default=0),
        ),
    ]
