# Generated by Django 5.0.3 on 2024-05-31 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code_client', models.CharField(default=None, max_length=50, unique=True)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('activite', models.CharField(max_length=255)),
                ('type_client', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Récurrent', 'Récurrent'), ('Potentiel', 'Potentiel'), ('Ancien', 'Ancien')], default=None, max_length=50)),
                ('categorie', models.CharField(choices=[('Premium', 'Premium'), ('Standard', 'Standard'), ('Basique', 'Basique'), ('VIP', 'VIP'), ('Or', 'Or'), ('Argent', 'Argent'), ('Bronze', 'Bronze'), ('Entreprise', 'Entreprise'), ('Individuel', 'Individuel')], default=None, max_length=50)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='clients/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_enquete', models.CharField(default='Nom par défaut', max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_questionnaire', models.CharField(choices=[('Feedback', 'Feedback'), ('Research', 'Research'), ('Satisfaction', 'Satisfaction')])),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes_enquete_client/')),
                ('clients', models.ManyToManyField(to='CRM.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('type_reclamation', models.CharField(choices=[('Service', 'Service'), ('Produit', 'Produit'), ('Facturation', 'Facturation'), ('Livraison', 'Livraison'), ('Support', 'Support')], default=None, max_length=50)),
                ('date_livraison', models.DateField()),
                ('gravite', models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Grave', 'Grave'), ('Critique', 'Critique')], default=None, max_length=50)),
                ('decisions', models.TextField(blank=True)),
                ('declencher_plan_action', models.BooleanField(default=False)),
                ('reclamation_fournisseur', models.FileField(blank=True, null=True, upload_to='reclamations_fournisseur/')),
                ('plan_action', models.FileField(blank=True, null=True, upload_to='plans_action/')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='fichiers_pdf_reclamation_client/')),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CRM.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_client_created', to=settings.AUTH_USER_MODEL)),
                ('responsable_traitement', models.ForeignKey(limit_choices_to={'groups__name': 'responsable_traitement'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_traitement', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamation_client_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type_suggestion', models.CharField(choices=[('FEATURE_REQUEST', 'Feature Request'), ('BUG_REPORT', 'Bug Report'), ('GENERAL_FEEDBACK', 'General Feedback')])),
                ('description', models.TextField()),
                ('actions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes_suggestion_client/')),
                ('client_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_created', to=settings.AUTH_USER_MODEL)),
                ('receptionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_fixe', models.DateField()),
                ('date_suivi', models.DateField()),
                ('rapport_suivi', models.TextField()),
                ('reclamation_cloturee', models.BooleanField(default=False)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_reclamation_created', to=settings.AUTH_USER_MODEL)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.reclamationclient')),
                ('responsable_suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi_reclamation_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
