# Generated by Django 5.0.3 on 2024-05-27 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
        ('fournisseur', '0002_alter_reclamationfournisseur_type_reclamation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Standard', 'Standard'), ('Basique', 'Basique'), ('VIP', 'VIP'), ('Or', 'Or'), ('Argent', 'Argent'), ('Bronze', 'Bronze'), ('Entreprise', 'Entreprise'), ('Individuel', 'Individuel')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='reclamationclient',
            name='gravite',
            field=models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Grave', 'Grave'), ('Critique', 'Critique')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='reclamationclient',
            name='responsable_traitement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_traitement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('Récurrent', 'Récurrent'), ('Potentiel', 'Potentiel'), ('Ancien', 'Ancien')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='reclamationclient',
            name='type_reclamation',
            field=models.CharField(choices=[('Service', 'Service'), ('Produit', 'Produit'), ('Facturation', 'Facturation'), ('Livraison', 'Livraison'), ('Support', 'Support')], default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='CategorieClient',
        ),
        migrations.DeleteModel(
            name='GraviteReclamation',
        ),
        migrations.DeleteModel(
            name='ResponsableTraitement',
        ),
        migrations.DeleteModel(
            name='TypeClient',
        ),
        migrations.DeleteModel(
            name='TypeReclamation',
        ),
    ]
