# Generated by Django 5.0.3 on 2024-05-31 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_clientenquete_name_enquete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionclient',
            name='client_concerne',
        ),
        migrations.AddField(
            model_name='clientenquete',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquete_created', to='CRM.client'),
        ),
        migrations.AddField(
            model_name='suggestionclient',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_created', to='CRM.client'),
        ),
    ]
