# Generated by Django 5.0.3 on 2024-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_client_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pieces_jointes',
            field=models.FileField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
