# Generated by Django 5.0.3 on 2024-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_client_pieces_jointes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_client',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
