# Generated by Django 5.0.3 on 2024-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_remove_suggestionclient_client_concerne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientenquete',
            name='name_enquete',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
