# Generated by Django 5.0.3 on 2024-05-27 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_client_code_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamationclient',
            name='client',
        ),
        migrations.AlterField(
            model_name='reclamationclient',
            name='responsable_traitement',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'responsable_traitement'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_traitement', to=settings.AUTH_USER_MODEL),
        ),
    ]
