# Generated by Django 5.0.3 on 2024-05-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_remove_reclamationclient_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamationclient',
            name='date',
        ),
        migrations.AlterField(
            model_name='reclamationclient',
            name='code',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
