# Generated by Django 5.0.3 on 2024-05-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_remove_reclamationclient_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamationclient',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CRM.client'),
        ),
    ]
