# Generated by Django 5.0.3 on 2024-04-15 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_object', models.CharField(max_length=255)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='demand_attachments/')),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'groups__name': 'redacteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='demand_rediges', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.type_document')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
