# Generated by Django 5.0.3 on 2024-04-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_demanddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('doc_int', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_versions', to='doc.docint')),
            ],
        ),
    ]
