# Generated by Django 5.0.3 on 2024-04-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_remove_historiqueversions_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriqueVersions',
        ),
    ]
