# Generated by Django 5.0.3 on 2024-05-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_historicaldocext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docint',
            name='selection_activite',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='docint',
            name='selection_site',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='docint',
            name='type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocint',
            name='selection_activite',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocint',
            name='selection_site',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocint',
            name='type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
