# Generated by Django 5.0.3 on 2024-05-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_alter_docint_selection_activite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanddocument',
            name='type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
