# Generated by Django 5.0.3 on 2024-05-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_remove_demanddocument_is_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docint',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Approuvé', 'Approuvé'), ('Vérifié', 'Vérifié'), ('Rejeté', 'Rejeté')], default='En cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldocint',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Approuvé', 'Approuvé'), ('Vérifié', 'Vérifié'), ('Rejeté', 'Rejeté')], default='En cours', max_length=20),
        ),
    ]
