# Generated by Django 5.0.3 on 2024-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_alter_docint_statut_alter_historicaldocint_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldocext',
            name='lieu_classement',
            field=models.CharField(choices=[('Archives', 'Archives'), ('Bureau', 'Bureau'), ('Entrepôt', 'Entrepôt'), ('Cloud', 'Cloud')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='docext',
            name='lieu_classement',
            field=models.CharField(choices=[('Archives', 'Archives'), ('Bureau', 'Bureau'), ('Entrepôt', 'Entrepôt'), ('Cloud', 'Cloud')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demanddocument',
            name='type',
            field=models.CharField(choices=[('Manuel', 'Manuel'), ('Procédure', 'Procédure'), ('Politique', 'Politique'), ('Rapport', 'Rapport'), ('Mémoire', 'Mémoire')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='docint',
            name='selection_activite',
            field=models.CharField(choices=[('Développement', 'Développement'), ('Test', 'Test'), ('Documentation', 'Documentation'), ('Déploiement', 'Déploiement'), ('Support', 'Support')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='docint',
            name='selection_site',
            field=models.CharField(choices=[('Site 1', 'Site 1'), ('Site 2', 'Site 2'), ('Site 3', 'Site 3'), ('Site 4', 'Site 4')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='docint',
            name='type',
            field=models.CharField(choices=[('Manuel', 'Manuel'), ('Procédure', 'Procédure'), ('Politique', 'Politique'), ('Rapport', 'Rapport'), ('Mémoire', 'Mémoire')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldocint',
            name='selection_activite',
            field=models.CharField(choices=[('Développement', 'Développement'), ('Test', 'Test'), ('Documentation', 'Documentation'), ('Déploiement', 'Déploiement'), ('Support', 'Support')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldocint',
            name='selection_site',
            field=models.CharField(choices=[('Site 1', 'Site 1'), ('Site 2', 'Site 2'), ('Site 3', 'Site 3'), ('Site 4', 'Site 4')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldocint',
            name='type',
            field=models.CharField(choices=[('Manuel', 'Manuel'), ('Procédure', 'Procédure'), ('Politique', 'Politique'), ('Rapport', 'Rapport'), ('Mémoire', 'Mémoire')], default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='Lieu_Classement',
        ),
    ]
