# Generated by Django 5.0.3 on 2024-05-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0012_alter_historicaldocext_lieu_classement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activite',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='Type_Document',
        ),
    ]
