# Generated by Django 5.0.3 on 2024-04-11 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RH', '0016_employe_is_user_employe_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraviteAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrioriteAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SourceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActionPrincipale',
            fields=[
                ('numero_sequentiel', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.TextField()),
                ('description', models.TextField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_action', to=settings.AUTH_USER_MODEL)),
                ('responsable_validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.employe')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_action', to=settings.AUTH_USER_MODEL)),
                ('cause_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.causeaction')),
                ('gravite_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.graviteaction')),
                ('priorite_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.prioriteaction')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.site')),
                ('source_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.sourceaction')),
                ('type_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.typeaction')),
            ],
        ),
        migrations.CreateModel(
            name='SousAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequentiel_sous_action', models.CharField(max_length=50)),
                ('delai_realisation', models.DateTimeField()),
                ('delai_suivi', models.DateTimeField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('action_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_actions', to='action.actionprincipale')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_sous_action', to=settings.AUTH_USER_MODEL)),
                ('gravite_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.graviteaction')),
                ('priorite_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.prioriteaction')),
                ('responsable_realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_realisees', to='RH.employe')),
                ('responsable_suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_suivies', to='RH.employe')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sous_action', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
