# Generated by Django 5.0.3 on 2024-06-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionprincipale',
            name='cause_action',
            field=models.CharField(choices=[('Human Error', 'Human Error'), ('Equipment Failure', 'Equipment Failure'), ('Process Gap', 'Process Gap')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actionprincipale',
            name='gravite_action',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actionprincipale',
            name='priorite_action',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actionprincipale',
            name='site',
            field=models.CharField(choices=[('New York', 'New York'), ('Los Angeles', 'Los Angeles'), ('Chicago', 'Chicago')], max_length=50),
        ),
        migrations.AlterField(
            model_name='actionprincipale',
            name='source_action',
            field=models.CharField(choices=[('Audit', 'Audit'), ('Customer Feedback', 'Customer Feedback'), ('Internal Review', 'Internal Review')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actionprincipale',
            name='type_action',
            field=models.CharField(choices=[('Corrective', 'Corrective'), ('Preventive', 'Preventive'), ('Improvement', 'Improvement')], max_length=20),
        ),
    ]
