# Generated by Django 5.0.3 on 2024-06-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_alter_actionprincipale_cause_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionprincipale',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_action/'),
        ),
    ]
