# Generated by Django 5.0.3 on 2024-04-22 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RH', '0020_clotureformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exigence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_reglementation', models.CharField(max_length=100)),
                ('applicable', models.BooleanField(default=False)),
                ('plan_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.planaction')),
            ],
        ),
        migrations.CreateModel(
            name='FicheExigenceReglementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('source_liste', models.CharField(max_length=100)),
                ('type_decideur', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creer_com', to=settings.AUTH_USER_MODEL)),
                ('exigence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformite.exigence')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_com', to=settings.AUTH_USER_MODEL)),
                ('type_fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformite.type_fiche')),
            ],
        ),
    ]
