# Generated by Django 5.0.3 on 2024-04-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformite', '0001_initial'),
        ('doc', '0007_historicaldocext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheexigencereglementaire',
            name='source_liste',
        ),
        migrations.AddField(
            model_name='ficheexigencereglementaire',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.docext'),
        ),
    ]
