# Generated by Django 5.0.3 on 2024-04-07 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_risk', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('date_declaration', models.DateField(verbose_name='Date de déclaration du risque')),
                ('declencheur', models.CharField(max_length=255, verbose_name='Déclencheur')),
                ('liste_concernee', models.TextField(verbose_name='Liste concernée')),
                ('type_risque', models.CharField(choices=[('MENACE', 'Menace'), ('OPPORTUNITE', 'Opportunité')], max_length=20, verbose_name='Type de risque')),
                ('criteres_evaluation', models.JSONField(verbose_name="Critères d'évaluation")),
                ('methode_calcul', models.CharField(choices=[('MOYENNE', 'Moyenne'), ('MAX', 'Maximum'), ('MIN', 'Minimum')], max_length=20, verbose_name='Paramétrage de méthode de calcul')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
