# Generated by Django 5.0.3 on 2024-04-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risque',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes/'),
        ),
    ]
