# Generated by Django 5.0.3 on 2024-06-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_remove_risque_criteres_evaluation_critereevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risque',
            name='declencheur',
            field=models.CharField(choices=[('Faille de sécurité dans le système', 'Faille de sécurité dans le système'), ('Attaque de phishing', 'Attaque de phishing'), ('Panne équipement', 'Panne équipement'), ('Erreur humaine', 'Erreur humaine')]),
        ),
        migrations.AlterField(
            model_name='risque',
            name='liste_concernee',
            field=models.CharField(choices=[('Département IT', 'Département IT'), ('Équipe de production', 'Équipe de production'), ('Clients', 'Clients'), ('Fournisseurs', 'Fournisseurs')]),
        ),
        migrations.AlterField(
            model_name='risque',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='pieces_jointes_risk/'),
        ),
    ]
