# Generated by Django 5.0.3 on 2024-06-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_alter_risque_declencheur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critereevaluation',
            name='note',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
