# Generated by Django 5.0.3 on 2024-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_remove_risque_criteres_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risque',
            name='nom_risk',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
